redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  dbIndex: 0
spring:
  application:
    name: app-be
server:
  port: 90
---
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/dbdev
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auo: none
---
#pageable configuration
pageable:
  page:
    size: 10
    number: 1
    sortBy: id
    sortType: desc